# Generated by Django 2.1.5 on 2021-08-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite', '0003_auto_20210804_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, upload_to='static\\images'),
        ),
    ]
