# Generated by Django 2.1.5 on 2021-08-05 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite', '0006_auto_20210805_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
