# Generated by Django 2.1.5 on 2021-08-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite', '0007_auto_20210805_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_list',
            name='game',
            field=models.ManyToManyField(blank=True, to='infinite.Game'),
        ),
    ]
