# Generated by Django 2.1.5 on 2021-08-06 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infinite', '0009_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_developer',
        ),
    ]
