# Generated by Django 2.1.5 on 2021-08-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite', '0010_remove_userprofile_is_developer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
