# Generated by Django 2.1.5 on 2021-08-06 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite', '0011_auto_20210806_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='released_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
