# Generated by Django 2.1.5 on 2021-08-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infinite', '0012_auto_20210806_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
